Repository Soumojitshome2023/nextjs-videocall-webapp, pull requests merged in 2024-10, with the labels that each got.

#16 Additon of All Contributors | Issue #10
  README.md
Labels: gssoc-ext, Hacktoberfest-accepted, level2, hacktoberfest

#17 Added custom error page for better user experience
  client/src/app/not-found.js
Labels: gssoc-ext, Hacktoberfest-accepted, level2, hacktoberfest

#14 Added:: Custom 404 Page and added meta tags, robots.txt, sitemap for SEO enhancement
  client/next-sitemap.config.js
  client/package.json
  client/public/robots.txt
  client/public/sitemap-0.xml
  client/public/sitemap.xml
  client/src/app/layout.js
  client/src/app/not-found.js
Labels: gssoc-ext, Hacktoberfest-accepted, level2, hacktoberfest

#19 Added header and footer
  client/package-lock.json
  client/src/app/layout.js
  client/src/components/Footer.css
  client/src/components/Footer.js
  client/src/components/Header.css
  client/src/components/Header.js
Labels: gssoc-ext, Hacktoberfest-accepted, level2, hacktoberfest

#35 Added signup page and login page
  client/package-lock.json
  client/package.json
  client/src/app/login/page.js
  client/src/app/signup/page.js
  client/src/app/socket.js
  client/src/components/Header.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#49 Added issues template Fixes #34
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/code_enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest, level1

#58 added contact links and icons in footer with original links
  client/package-lock.json
  client/package.json
  client/src/components/Footer.css
  client/src/components/Footer.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#81 Adding Dark mode / Light mode Toggle button
  client/src/app/globals.css
  client/src/app/layout.js
  client/src/components/Header.css
  client/src/components/Header.js
  client/tailwind.config.js
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest
